-- Apply manually to the user's Supabase project. Public read; admin-only writes.
begin;
create table if not exists public.surahs(id int primary key check(id between 1 and 114),name_arabic text not null,name_english text,type text not null,total_ayahs int not null check(total_ayahs>0));
create table if not exists public.ayahs(id bigint primary key,surah_id int not null references public.surahs(id),ayah_number int not null,text_arabic text not null,text_english text,unique(surah_id,ayah_number));
create table if not exists public.tafsir(id bigint generated by default as identity primary key,ayah_id bigint not null unique references public.ayahs(id),tafsir_text text not null,source text not null);
create table if not exists public.athkar_categories(id int primary key,name text not null,icon text);
create table if not exists public.athkar(id int primary key,category_id int not null references public.athkar_categories(id),text text not null,repeat_count int not null check(repeat_count>0),reference text not null,source_url text);
create table if not exists public.dua_categories(id int primary key,name text not null);
create table if not exists public.duas(id int primary key,category_id int not null references public.dua_categories(id),title text,text text not null,reference text not null,source_url text);
create table if not exists public.hadith_collections(id int primary key,name text not null,description text);
create table if not exists public.hadiths(id bigint primary key,title text not null,text_arabic text not null,sharh text not null,grade text not null,reference text not null,source_url text not null,source_version text not null,word_meanings text,benefits text,book_names text[] not null default '{}',categories text[] not null default '{}',source_payload jsonb not null);
create table if not exists public.prophets(id int primary key,slug text not null unique,name text not null,summary text not null,full_story jsonb not null);
create table if not exists public.content_versions(source text primary key,version text not null,metadata jsonb not null);
create index if not exists ayahs_surah_idx on public.ayahs(surah_id,ayah_number);
create index if not exists hadiths_books_idx on public.hadiths using gin(book_names);
create index if not exists hadiths_categories_idx on public.hadiths using gin(categories);
do $$ declare tablename text; begin
 foreach tablename in array array['surahs','ayahs','tafsir','athkar_categories','athkar','dua_categories','duas','hadith_collections','hadiths','prophets','content_versions'] loop
 execute format('alter table public.%I enable row level security',tablename);
 execute format('revoke all on public.%I from anon, authenticated',tablename);
 execute format('grant select on public.%I to anon, authenticated',tablename);
 execute format('drop policy if exists public_read on public.%I',tablename);
 execute format('create policy public_read on public.%I for select to anon, authenticated using (true)',tablename);
 end loop;
end $$;
commit;
