'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Play, Pause, Moon, Sun, BookOpen, ChevronDown, ArrowRight, ArrowLeft, Volume2 } from 'lucide-react';
import { arabic } from './ui';
import { supabase } from '@/lib/supabase';
export type Ayah={id:number,surah_id:number,ayah_number:number,text_arabic:string,tafsir_text:string,source:string};
export function Reader({surah,initial}:{surah:number,initial:Ayah[]}){
 const [ayahs,setAyahs]=useState(initial);const [expanded,setExpanded]=useState<number|null>(null);const [font,setFont]=useState(32);const [dark,setDark]=useState(false);const [playing,setPlaying]=useState<number|null>(null);const [error,setError]=useState('');const [warning,setWarning]=useState('');const audio=useRef<HTMLAudioElement|null>(null);
 useEffect(()=>{try{setDark(localStorage.getItem('am-reader-dark')==='true');const v=Number(localStorage.getItem('am-reader-font'));if(v>=24&&v<=48)setFont(v)}catch{};return()=>{audio.current?.pause()}},[]);
 useEffect(()=>{if(!supabase)return;let active=true;(async()=>{try{const {data,error}=await supabase!.from('ayahs').select('id,surah_id,ayah_number,text_arabic,tafsir(tafsir_text,source)').eq('surah_id',surah).order('ayah_number');if(error)throw error;if(data?.length===initial.length&&active)setAyahs(data.map((a,i)=>({...initial[i],...a,tafsir_text:a.tafsir?.[0]?.tafsir_text||initial[i].tafsir_text,source:a.tafsir?.[0]?.source||initial[i].source})))}catch{if(active)setWarning('تعذّر التحديث. تُعرض النسخة المضمّنة من القرآن والتفسير.')}})();return()=>{active=false}},[surah,initial]);
 function changeFont(v:number){setFont(v);try{localStorage.setItem('am-reader-font',String(v))}catch{}}
 function changeDark(){setDark(!dark);try{localStorage.setItem('am-reader-dark',String(!dark))}catch{}}
 async function play(id:number){setError('');if(playing===id){audio.current?.pause();setPlaying(null);return}audio.current?.pause();const a=new Audio(`https://cdn.islamic.network/quran/audio/128/ar.alafasy/${id}.mp3`);audio.current=a;setPlaying(id);a.onended=()=>setPlaying(null);a.onerror=()=>{setError('تعذّر تشغيل التلاوة. تحقق من اتصالك بالإنترنت وحاول مجددًا.');setPlaying(null)};try{await a.play()}catch{if(audio.current===a){setPlaying(null);setError('تعذّر تشغيل التلاوة. حاول مرة أخرى.')}}}
 return <section className={'reader '+(dark?'dark':'')}><div className="container content-section"><div className="reading-width"><div className="reader-controls"><BookOpen size={20}/><span className="desktop-only">خيارات القراءة</span><div className="font-buttons"><label htmlFor="font-size">حجم الخط</label><input id="font-size" type="range" min="24" max="48" value={font} onChange={e=>changeFont(Number(e.target.value))}/><button className="icon-button" onClick={changeDark} aria-label={dark?'الوضع النهاري':'الوضع الليلي'} aria-pressed={dark}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></div></div><p className="source-line" style={{margin:'0 0 24px'}}><Volume2 size={15}/>التلاوة: مشاري راشد العفاسي · تتطلب اتصالًا بالإنترنت</p>{warning&&<p className="notice" role="status">{warning}</p>}{error&&<p className="notice error-notice" role="alert">{error}</p>}{ayahs.map(a=><article key={a.id} id={'ayah-'+a.ayah_number} className="content-card"><div className="card-top"><span className="ayah-number">{arabic(a.ayah_number)}</span><span>الآية {arabic(a.ayah_number)}</span></div><p className="sacred" style={{fontSize:font+'px'}}>{a.text_arabic}</p><div className="card-actions"><button className="button secondary" onClick={()=>void play(a.id)} aria-label={(playing===a.id?'إيقاف':'تشغيل')+' الآية '+arabic(a.ayah_number)}>{playing===a.id?<Pause size={16}/>:<Play size={16}/>} {playing===a.id?'إيقاف':'استماع'}</button><button className="button secondary" onClick={()=>setExpanded(expanded===a.id?null:a.id)} aria-expanded={expanded===a.id} aria-controls={'tafsir-'+a.id}><BookOpen size={16}/>التفسير<ChevronDown size={15}/></button></div>{expanded===a.id&&<div className="explanation" id={'tafsir-'+a.id}><h4>{a.source}</h4><p style={{color:'inherit'}}>{a.tafsir_text}</p></div>}</article>)}<div className="pager">{surah>1?<Link className="button secondary" href={'/quran/'+(surah-1)+'/'}><ArrowRight size={16}/>السورة السابقة</Link>:<span/>}<Link className="button secondary" href="/quran/">فهرس السور</Link>{surah<114?<Link className="button secondary" href={'/quran/'+(surah+1)+'/'}>السورة التالية<ArrowLeft size={16}/></Link>:<span/>}</div></div></div></section>
}
